### ISSUE TITLE
Is it expected that the UFW rules block traffic to the multicast domain?

### ISSUE THREAD

**Issue by KoenDG** [konstruktoid/ansible-role-hardening#105]
Looking at `/var/log/ufw.log`, I'm seeing blocked traffic with `DST=224.0.0.1`

Which, looking that up: https://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml

Is a multicast address. From what I'm reading, this is basic network functionality. However, I assume it might be abused for attacks?

Is this to be blocked at all, considering it is such basic functionality?

And if so, is there a way to not log UFW blocks on this specific subnet? Like, tell UFW to not log anything going over 224.0.0.0/24 ?

Not really a bug, I guess, though in terms of functionality and generated logs, is kind of weird to see these show up in the logs. And after a while gets annoying to have to ignore them and look for other stuff in between them.

**Comment by konstruktoid** [comment]
By default traffic in any direction is blocked, with some ports allowed out (https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/firewall.yml#L135-L148) and `ssh` allowed in (https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/firewall.yml#L120-L133)

**Comment by KoenDG** [comment]
Yeah, looking at this I'm basically asking to either not block, or block but don't log that.

Not a great idea. My bad.
