### ISSUE TITLE
Feature request: have. a switch to disable ipv6  completely

### ISSUE THREAD

**Issue by oferchen** [konstruktoid/ansible-role-hardening#118]
Is it possible to add a switch to disable ipv6 it completely? seems to be a pretty common use case.

**Comment by konstruktoid** [comment]
Hi @oferchen, absolutely. I'll add it in a couple of days.

**Comment by konstruktoid** [comment]
hi again, could you please test https://github.com/konstruktoid/ansible-role-hardening/pull/119?

**Comment by konstruktoid** [comment]
#119 has been merged.
