### ISSUE TITLE
Is there a reason sysctl values are cast to integer?

### ISSUE THREAD

**Issue by KoenDG** [konstruktoid/ansible-role-hardening#149]
See here: https://github.com/konstruktoid/ansible-role-hardening/blob/5c4e9ade9f3d961d7681a80bfc139a7f679c7e97/tasks/sysctl.yml#L46

Certain values can have more than 1 setting. Example:

```
net.ipv4.tcp_wmem: 4096 87380 8388608
```

Granted, that isn't a security/hardening related setting. So I'm just wondering if it would be ok to remove the cast, or leave it in as long as it doesn't come up for a hardening-related idea.

**Comment by konstruktoid** [comment]
No particular reason except that all defaults (https://github.com/konstruktoid/ansible-role-hardening/blob/master/defaults/main/sysctl.yml) are basic integers.

If other values are added that isn't integers, the cast should be removed.

**Comment by KoenDG** [comment]
Alright, since there appears to be no need for that right now, I'll close this.
