### ISSUE TITLE
[BUG] When disabling ufw_enable playbook fails when setting sysctl for conntrack with default values

### ISSUE THREAD

**Issue by 5t0ne** [konstruktoid/ansible-role-hardening#201]
**Describe the bug**
When disabling ufw module, I get an error in the `Configure sysctl` task due to missing `nf_conntrack_max `and `nf_conntrack_tcp_loose `files.

**To Reproduce**
Setup a fresh basic Ubuntu 22.04 machine and run the hardening role against it with ufw deactivated

**Expected behavior**
When not activating ufw, it should also not try to set configurations that are dependent on packages that are installed by ufw. In this case the nf_conntrack module is installed in the setup procedure of ufw. If that is not processed, the `Configure sysctl` task will fail with the default variables.

**Additional context**
Now we could state that this can be fixed by modifying the default variables for sysctl, but I think if a flag is offered to include or not a module, it should work on it's own.

So to options to achieve this from my point of view:
1. We could pull out the setting of those 2 in a separate step and just run this, when ufw_enable = true
2. We can move the setting of this 2 parameters into the ufw tasks file to have all ufw related tasks together

I can create a pull request if you want me to change this.

**Comment by konstruktoid** [comment]
Good catch @5t0ne, I'll move those into the ufw tasks.

**Comment by konstruktoid** [comment]
I've merged https://github.com/konstruktoid/ansible-role-hardening/pull/202, hopefully that will fix it
