### ISSUE TITLE
make sshd config ClientAliveInterval configurable

### ISSUE THREAD

**Issue by iTaybb** [konstruktoid/ansible-role-hardening#22]
I'd like to use a custom ClientAliveInterval in the sshd_config. I'm using commands that might take up to 10m to complete, and the current default configuration (5m) disconnects the session in the middle.

**Comment by konstruktoid** [comment]
Hi @iTaybb for creating this issue. I'm in the process of replacing the static `sshd_config` with variables and should be finished soon(tm).

**Comment by konstruktoid** [comment]
I believe this has been fixed with https://github.com/konstruktoid/ansible-role-hardening/commit/b9299ae9eea51a7d00b8ba8bef80655d965f0a4a#diff-7eeda618087b49ae876084ab6c73fdbbR107-R145

**Comment by iTaybb** [comment]
This looks great. Thanks.
