### ISSUE TITLE
Lynis question

### ISSUE THREAD

**Issue by quetzalsly** [konstruktoid/ansible-role-hardening#23]
Thanks very much for your hard work on this repo, I just recently switched to linux in general. I plan to run a Lubuntu VPS which doesn't interact with the outside world but allows an admin to remote desktop in.

I spent a few weeks reading linux books and learning about  various hardening techniques and mainly UFW. Then I discovered ansible and found this repo, I was very intrigued to see if a script can perform a '1 click' hardening of the entire system.

I did get a few errors running your script but most of the results seemed to go ok. I rebooted the system and it seems to be fine although I had some concerns, avahi is gone but what about bluetooth service? does a server really need bluetooth lol? seems like a security nightmare to me, but then again I have very little experience in security in general.

My other concern was that I ran Lynis and there was a huge amount of UNSAFE, WARNING and so on. My OCD is really triggering me and thinking I should have a 100% Lynis score but the hardening index is only 87.

Please can you let me know is your script enough to make a server secure on a VPS? I am just so paranoid about these things.

Thanks

**Comment by konstruktoid** [comment]
Hi @quetzalsly and thanks for the kind words.

`avahi` is removed by the package task, see https://github.com/konstruktoid/ansible-role-hardening/blob/master/defaults/main/packages.yml#L6-L7 and the `bluetooth` kernel module should be blocked, have a look in `/etc/modprobe.d/disablemod.conf` (https://github.com/konstruktoid/ansible-role-hardening/blob/master/defaults/main/module_blocklists.yml#L12).

I haven't tested this on Lubuntu (https://lubuntu.net/ ?) so I can't really answer regarding the Lynis result without actually seeing the report or log.

If you have any errors running this playbook, feel free to attach logs and comments.

**Comment by quetzalsly** [comment]
Maybe you can try run it in a vm to test if you have time? its just a daily build from here: 

http://cdimage.ubuntu.com/lubuntu/daily-live/pending/

I would post my logs but I am not sure where to find everything, I am still learning how linux works. But if you are busy then I will do my best to provide logs in a few days. It would be really cool to have this script work across all ubuntu variants.

**Comment by konstruktoid** [comment]
Installed Lubuntu 20.10 and had no issues with the playbook (I skipped Aide to speed things up).

```
$ ansible-playbook -c local tests/test.yml --extra-vars "sshd_admin_net=0.0.0.0/0" -K --skip-tags aide
[...]
PLAY RECAP **************************************************************************************************************
127.0.0.1                  : ok=140  changed=7    unreachable=0    failed=0    skipped=46   rescued=0    ignored=4  
```

Running Lynis on a system after reboot:

```
  * Set a password on GRUB boot loader to prevent altering boot configuration (e.g. boot in single user mode without password) [BOOT-5122]
      https://cisofy.com/lynis/controls/BOOT-5122/
```

GRUB boot loader password is not set since this would cause loads of work when working with VPS et al.

```
  * Consider hardening system services [BOOT-5264]
    - Details  : Run '/usr/bin/systemd-analyze security SERVICE' for each service
      https://cisofy.com/lynis/controls/BOOT-5264/
```

.services need to be configured and tested individually and this is out-of-scope for this playbook.

```
  * Check PAM configuration, add rounds if applicable and expire passwords to encrypt with new values [AUTH-9229]
      https://cisofy.com/lynis/controls/AUTH-9229/
```

Set new passwords for the existing users, the system aren't using the configured settings since the user and password were created before the configuration changes.

```
  * When possible set expire dates for all password protected accounts [AUTH-9282]
      https://cisofy.com/lynis/controls/AUTH-9282/
```

Set expire dates for all password protected accounts.

```
  * To decrease the impact of a full /home file system, place /home on a separate partition [FILE-6310]
      https://cisofy.com/lynis/controls/FILE-6310/

  * To decrease the impact of a full /var file system, place /var on a separate partition [FILE-6310]
      https://cisofy.com/lynis/controls/FILE-6310/
```

I've been lazy and haven't partitioned the test system, and most VPS aren't.

```
  * Install package apt-show-versions for patch management purposes [PKGS-7394]
      https://cisofy.com/lynis/controls/PKGS-7394/
```

Might be worth adding `apt-show-versions` to the playbook but low priority.

```
  * Access to CUPS configuration could be more strict. [PRNT-2307]
      https://cisofy.com/lynis/controls/PRNT-2307/

  * Check CUPS configuration if it really needs to listen on the network [PRNT-2308]
      https://cisofy.com/lynis/controls/PRNT-2308/
```

CUPS is out-of-scope.

```
  * Check iptables rules to see which rules are currently not used [FIRE-4513]
      https://cisofy.com/lynis/controls/FIRE-4513/
```

UFW configuration is not adapted to a graphical environment with CUPS, audio etc etc

```
  * Consider hardening SSH configuration [SSH-7408]
    - Details  : ClientAliveCountMax (set 3 to 2)
      https://cisofy.com/lynis/controls/SSH-7408/

  * Consider hardening SSH configuration [SSH-7408]
    - Details  : MaxSessions (set 3 to 2)
      https://cisofy.com/lynis/controls/SSH-7408/

  * Consider hardening SSH configuration [SSH-7408]
    - Details  : Port (set 22 to )
      https://cisofy.com/lynis/controls/SSH-7408/
```

Depending on which benchmark or policy you're reading the values are acceptable, but can be changed with the available variables.

```
  * Enable logging to an external logging host for archiving purposes and additional protection [LOGG-2154]
      https://cisofy.com/lynis/controls/LOGG-2154/
```

Out-of-scope.

```
  * Check what deleted files are still in use and why. [LOGG-2190] 
      https://cisofy.com/lynis/controls/LOGG-2190/
```

On my system some audio things caused this, restart of services or reboot usually fixes this.

```
  * Enable sysstat to collect accounting (no results) [ACCT-9626] 
      https://cisofy.com/lynis/controls/ACCT-9626/
```

Will be added soon(tm).

```
  * Double check the permissions of home directories as some might be not strict enough. [HOME-9304] 
      https://cisofy.com/lynis/controls/HOME-9304/
```

The home directory for the initial user where created before the configuration changes.

```
  * Harden compilers like restricting access to root user only [HRDN-7222]
      https://cisofy.com/lynis/controls/HRDN-7222/
```

Will be added soon(tm).

**Comment by quetzalsly** [comment]
Thanks so much for the detailed review! what was the final score you got? and would you personaly be happy having this server being open to public? (assuming firewall is setup etc).

**Comment by konstruktoid** [comment]
I personally would not publish anything using Lubuntu or any other distribution with a installed GUI or other user space tools installed (CUPS, audio, bluetooth, and so on).

- Use a server release
- Run the Ansible playbook (or similar)
- Ensure only needed firewall ports are open
- Install the wanted service (eg web server)
- Follow best practices regarding that service
- Only allow specific users, never root, access
- Disable ssh password authentication
- Keep the server patched

**Comment by quetzalsly** [comment]
Thanks, I had some more questions which im unsure about: 

1) I was just wondering how does this ansible hardening currently differ from your normal hardening using the sh script? which one has more features etc? Should I be running the other script first?

2) Do any of the fixes in this repo affect system speed? Ideally I would like maximum performance.

3) After running this script I still get "No AIDE database was found" in Lynis.

**Comment by konstruktoid** [comment]
The https://github.com/konstruktoid/hardening contains some `sed` modifications missing in this repo, but it shouldn't affect any scoring.

The big difference is its usage, the script is basically one-shot to create a golden image for installations and this Ansible repo is for continuous administration of existing servers.

I don't know to be honest, I don't think so but I haven't done any form of performance testing.

I'll have a look at the "No AIDE database was found" message.

**Comment by konstruktoid** [comment]
Are you using Lubuntu when getting the "No AIDE database was found" message? I'm asking because it didn't show up in our earlier discussion.

**Comment by quetzalsly** [comment]
Yes im using lubuntu 20.10 with removed extra packages so its basically ubuntu server + lightweight desktop environment.

**Comment by konstruktoid** [comment]
Ah, 20.10. I just filed a bug about Aide: https://bugs.launchpad.net/ubuntu/+source/aide/+bug/1903298
