### ISSUE TITLE
[BUG] User locked out if not in *sudo* group

### ISSUE THREAD

**Issue by gimiki** [konstruktoid/ansible-role-hardening#326]
**Describe the bug**
With default vars, a user can inhibit himself from accessing with ssh if the ssh user that runs the hardening role is not a member of the _sudo_ group.

**To Reproduce**
- Use default vars
- User is NOT in _sudoers_ group
- User is configured as privileged in /etc/sudoers `ansible ALL=(ALL) NOPASSWD: ALL`

User is then used as *ansible_user* to connect in ssh to the target host and run the hardening role.

**Expected behavior**
With default vars, I don't want to be locked out if I don't configure _sshd_allow_groups_.

**Additional context**
Ubuntu 20.04

A possible solution is to add a new variable _sshd_allow_users_ that defaults to `{{ ansible_user }}`.
Then in [templates/etc/ssh/sshd_config](https://github.com/konstruktoid/ansible-role-hardening/blob/2d8b519503d73aec842fc1605175feed38ae5a55/templates/etc/ssh/sshd_config.j2) add the `AllowUsers` option.

**Comment by konstruktoid** [comment]
Hi @gimiki 
Yeah, that makes sense.

Do you want to submit  PR?

**Comment by konstruktoid** [comment]
Awesome, thanks!
