### ISSUE TITLE
Just making sure, linter side effects?

### ISSUE THREAD

**Issue by KoenDG** [konstruktoid/ansible-role-hardening#334]
I noticed the linter PR that happened recently, going over the changes I saw this: https://github.com/konstruktoid/ansible-role-hardening/commit/dc74d5e16bccdba33299c4131f025645b45fb580#diff-fcd28e14d2fd61f927943dda8ea80c2246e8bde10b1ee74a608ed12a3ca5bf2fL47

Those strings like: `"^action_mail_acct ="` got their `"` removed, but not `"^admin_space_left_action = "` which specifically has an extra space after it.

Which has me thinking: is that correct? Should just that one have an extra space at the end, or is it all of them? Or the ending space is erronous?

Just making sure, I don't know auditd so well.

**Comment by konstruktoid** [comment]
Thanks @KoenDG, I'll take a closer look

**Comment by konstruktoid** [comment]
I believe it's just a consequence of me forgetting to remove that extra space, will clean that up.
I'll double check later on, but the test verifies that `admin_space_left_action = {{ auditd_admin_space_left_action }}` and it passes. 

```yaml
defaults/main/auditd.yml:auditd_admin_space_left_action: suspend
molecule/default/verify.yml:        - admin_space_left_action = {{ auditd_admin_space_left_action }}
```

**Comment by KoenDG** [comment]
Ok, thought I'd bring it up, as it's this lone item that stays with the extra space.

**Comment by konstruktoid** [comment]
Thanks for doing so, you never know
