### ISSUE TITLE
Disabeling snap removal on playbook

### ISSUE THREAD

**Issue by stav-sheen** [konstruktoid/ansible-role-hardening#336]
Hi, this is also actually not a bug but a follow-up on [the original issue here ](https://github.com/konstruktoid/hardening/issues/123)
specifically in regard to the playbook.
when running the playbook the server is left without snapd and its respective packages.
my use-case is similar to the one discussed in the issue linked above
I would love to know if there is a way to add the KEEP_SNAP flag or if you can advise on how to do this with the playbook.

os_version: ubuntu 22.04

Thank you! :)

**Comment by konstruktoid** [comment]
Hi again @stav-sheen, I believe this now have been fixed (https://github.com/konstruktoid/ansible-role-hardening/pull/339)

**Comment by stav-sheen** [comment]
amazing thank you very much !
