### ISSUE TITLE
[Documentation] Source(s) of password list?

### ISSUE THREAD

**Issue by RobertKosten** [konstruktoid/ansible-role-hardening#344]
It would be nice to know what source(s) are used for the password list. It is apparently updated more often than the usual Kali lists, so I'm assuming it's something else?

**Comment by konstruktoid** [comment]
Hi @RobertKosten 
The password list is generated using https://github.com/konstruktoid/hardening/blob/master/misc/genPasswordList.sh 

A related project is https://github.com/konstruktoid/honeypot-passwords, and it will be updated soonish
