### ISSUE TITLE
[BUG] Interface with vlan name notworking

### ISSUE THREAD

**Issue by sgnsys3** [konstruktoid/ansible-role-hardening#404]
**Describe the bug**
When running on a system with an interface VLAN name like bond0.101.
We will find the error sysctl path not found.

**To Reproduce**
1. Setup a new VM with vlan interface like ens19.101
2. Run ansible

**Expected behavior**
Running Ansible without errors but we found a sysctl path not found error.

**System (lsb_release -a or similar):**
Ubuntu 22.04

**Comment by konstruktoid** [comment]
Closed by #405
