### ISSUE TITLE
[Question] Disable SSHD?

### ISSUE THREAD

**Issue by Smana** [konstruktoid/ansible-role-hardening#466]
Hey,

First of all congrats for this great work. I just discovered the repository so please forgive my dumb question:

Would that makes sense to completely disable the sshd configuration and installation?

The idea is to leverage SSM on AWS or to configure something like Tailscale SSH.

If this is not the right place to ask, please tell me where I can reach out to you

Regards,
Smana

**Comment by konstruktoid** [comment]
Hi @Smana and it would make total sense to disable SSH if the service isn't needed, I did this for my honeypot role (https://github.com/konstruktoid/ansible-cowrie-rootless)

**Comment by Smana** [comment]
Great, thank you @konstruktoid. Closing this issue as I got my answer :) I'll have a closer look to the repo you mentioned
