### ISSUE TITLE
Past commit change altered code inconsistently

### ISSUE THREAD

**Issue by KoenDG** [konstruktoid/ansible-role-hardening#537]
Looking at the commits of the last few weeks and I run into this: https://github.com/konstruktoid/ansible-role-hardening/commit/ded07017d673eaa9842f9e82c8c92f68749e56fd#diff-e859dde9a1e131eb9dd0766f31c9a43e88a3818ca8b4f882faf98a8729b5d9d7

In tasks/aide.yml.

The old code looks like this, on line 165:
```
when: ansible_os_family == "RedHat" and not rhelaidedbnew.stat.exists
```

And the new code like this:
```
  when:
    - ansible_os_family == "RedHat"
    - rhelaidedbnew.stat.exists
```

That's not the same code. The `not` was removed. What used to be `A && !B` is now `A && B`. And there's a few more like that.

Is this intended?

**Comment by konstruktoid** [comment]
Nope, that's a bug, accidentally wiped that `not`.

**Comment by KoenDG** [comment]
Far as I was able to tell, that commit and the `aide` role was the only affected

**Comment by konstruktoid** [comment]
Yeah, I'll go over it all again and fix the aide task.

Thanks for the report @KoenDG
