### ISSUE TITLE
rkhunter SSH v1

### ISSUE THREAD

**Issue by cleberb** [konstruktoid/ansible-role-hardening#554]
SSH v1 is no longer supported by ssh. I recommend changing the rkhunter parameter to `ALLOW_SSH_PROT_V1=2` for not received warning.

https://www.openssh.com/txt/release-7.6:
```
 * ssh(1): delete SSH protocol version 1 support, associated
   configuration options and documentation.
```

https://github.com/konstruktoid/ansible-role-hardening/blob/f191e1a492fb5642cd73ce52e4159e30c54ceed7/tasks/rkhunter.yml#L29

**Comment by konstruktoid** [comment]
thanks @cleberb, will update the `rkhunter` task

**Comment by konstruktoid** [comment]
update merged
