### ISSUE TITLE
[BUG] When running on Debian, all tasks with installing or uninstalling packages are failing

### ISSUE THREAD

**Issue by limosek** [konstruktoid/ansible-role-hardening#59]
Thank you for your great repo!

**Describe the bug**
Using this playbook:
```
---
- hosts: www
  user: root
  any_errors_fatal: true
  tasks:
    - include_role:
        name: konstruktoid.hardening
      vars:
        - sshd_admin_net:
            - 1.2.3.0/24
        - ufw_outgoing_traffic:
            - 22
            - 53
            - 80
            - 123
            - 443
            - 853
            - 3128
            - 10051
```
To success this task, I need to manually remove/install packages. All apt commands ends with:
```
TASK [konstruktoid.hardening : debian family package installation] ***********************************************************
fatal: [1.2.3.4]: FAILED! => {"changed": false, "cmd": "None -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install audispd-plugins -o APT::Install-Recommends=no", "msg": "[Errno 2] No such file or directory: b'None': b'None'", "rc": 2}
```
Not sure why apt is not found and 'None' is used.

**Expected behavior**
Packages should be installed/deinstalled

**System (lsb_release -a or similar):**
ansible client and server:
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Additional context**
Tried to create other playbook just to install/deinstall packages by apt and everything works.
So it must be some defaults inside your tree but I was not able to find it.

**Comment by konstruktoid** [comment]
Hi @limosek and thank you.
I haven't seen this behaviour before, which ansible version are you using?

**Comment by limosek** [comment]
I have never seen this before too. I had an old ansible and I saw that minimal version is 2.10 so I have updated it.
It seems to be somewhere in apt module. Seems that it cannot find apt/apt-get/aptitude (all installed).
We will try to debug more locally. I tried to run with debug but I did not find any reason why simple package install/deinstall fails.

```
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lm/.local/lib/python3.7/site-packages/ansible
  executable location = /home/lm/.local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

Thank you!

Btw: Tried from two independent hosts with same results.
And tried this simple playbook which simply works (I was able to install/uninstall auditd):
```
- name: debian family package installation
  become: 'yes'
  hosts: www
  user: root
  tasks:
    - name: test
      apt:
        name: auditd
        state: present
        install_recommends: 'no'
```
Simple difference is that you use become=yes, I used root account to connect (will be disabled by hardenize).
I will try once more with become.

**Comment by limosek** [comment]
So tried with become=yes and result is same.

**Comment by konstruktoid** [comment]
Very odd, I've been running a few tests on my own and haven't been able to trigger this.
Can you include a verbose log for the `konstruktoid.hardening : debian family package installation` task?

**Comment by limosek** [comment]
We will do more tests here and will gather more info.
Thank you!

**Comment by limosek** [comment]
I have tried more things like change version of ansible but result was same.
I was able to make it working by uncommenting autoremove and autoclean.
Not sure why these options have this impact.

```
- name: remove unneeded debian dependency packages
  become: 'yes'
  apt:
#    autoclean: 'yes'
#    autoremove: 'yes'
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - packages
```
Will try on other host to be sure.

**Comment by konstruktoid** [comment]
Thanks for the follow up but do you mean that the `konstruktoid.hardening : debian family package installation` failure is related to the `remove unneeded debian dependency packages` task apt options?

**Comment by limosek** [comment]
Tried on other host and unfortunately, same result, even with commented lines.
Tried to debug ansible apt module. Running it directly on server finishes successfuly. Running via hardenize fails that it cannot find apt-get. (None).

This is really strange. Seems like apt module cannot find apt-get in bin_path.

**Comment by konstruktoid** [comment]
Besides running the standard `molecule` tests, I also tested with a Vagrant box again but I can't reproduce this.

Vagrant box:
```console
  config.vm.define "buster" do |buster|
    buster.vm.box = "bento/debian-10"
    buster.ssh.insert_key = true
    buster.vm.network "private_network", ip: "10.2.0.5"
    buster.vm.hostname = "buster"
  end
```

```sh
~$ sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install git python3-pip
~$ pip3 install ansible ansible-base
~$ git clone https://github.com/konstruktoid/ansible-role-hardening
~$ cd ansible-role-hardening
~$ sudo mkdir -p /etc/ansible/roles/konstruktoid.hardening/
~$ sudo cp -R ./* /etc/ansible/roles/konstruktoid.hardening/
~$ ~/.local/bin/ansible-playbook -i '127.0.0.1,' -e 'sshd_admin_net=0.0.0.0/0 sshd_allow_groups="vagrant sudo"' -c local tests/test.yml
[...]
PLAY RECAP *************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=185  changed=111  unreachable=0    failed=0    skipped=72   rescued=0    ignored=0
~$ sudo reboot
[ reboot and login ]
~$ cd ansible-role-hardening
~$ ~/.local/bin/ansible-playbook -i '127.0.0.1,' -e 'sshd_admin_net=0.0.0.0/0 sshd_allow_groups="vagrant sudo"' -c local tests/test.yml
[...]
PLAY RECAP *************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=173  changed=1    unreachable=0    failed=0    skipped=77   rescued=0    ignored=0
```

**Comment by konstruktoid** [comment]
After the above plays, connection from the local machine to the Vagrant box:
```sh
~$ ansible-playbook -u vagrant -i '127.0.0.1,' -e 'ansible_port=2222 ansible_ssh_private_key_file=./.vagrant/machines/buster/virtualbox/private_key sshd_admin_net=0.0.0.0/0 sshd_allow_groups="vagrant sudo"' tests/test.yml
[...]
PLAY RECAP *************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=174  changed=2    unreachable=0    failed=0    skipped=77   rescued=0    ignored=0
```

**Comment by limosek** [comment]
After lot of investigation, I have found that PATH variable is missing /usr/bin directory so apt-get was not found.
Even apparmor target was failing due to this. Global setting of PATH does not work for me.
I needed to add environment PATH variable directly to specific task. Not sure where the PATH is overwritten within script.

```
- name: remove unneeded debian dependency packages
  become: 'yes'
  apt:
    autoclean: 'yes'
    autoremove: 'yes'
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - packages
  environment:
    PATH: /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin|
```

**Comment by konstruktoid** [comment]
Can you check the output of `sudo grep secure_path /etc/sudoers`?

All changes made to the PATH variable, should include `/usr/bin`:
```sh
tasks/path.yml:    line: 'PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/snap/bin"'
templates/etc/login.defs.j2:ENV_PATH PATH=/usr/local/bin:/usr/bin:/bin
templates/etc/login.defs.j2:ENV_SUPATH PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
templates/etc/profile.d/initpath.sh.j2:  export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
templates/etc/profile.d/initpath.sh.j2:  export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/snap/bin
```

**Comment by limosek** [comment]
sudo grep secure_path /etc/sudoers
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

**Comment by limosek** [comment]
Let us close this. It must be something local here. I have workaround. 
But it is really strange..
Thank you!
