### ISSUE TITLE
[BUG]  bullseye_vlan Unable to start service usbguard: Job for usbguard.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by jdaln** [konstruktoid/ansible-role-hardening#590]
Hello!

First of all, thank you very much for the excellent repo and sharing it to the world!
It seems that even someone at the US CISA is using it! https://github.com/cisagov/ansible-role-hardening-2/

**Describe the bug**
Running `vagrant up` results in 
```
TASK [konstruktoid.hardening : Start and enable USBGuard] **********************
fatal: [bullseye_vlan]: FAILED! => {"changed": false, "msg": "Unable to start service usbguard: Job for usbguard.service failed because the control process exited with error code.\nSee \"systemctl status usbguard.service\" and \"journalctl -xe\" for details.\n"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
bullseye_vlan              : ok=65   changed=30   unreachable=0    failed=1    skipped=14   rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**To Reproduce**
Run `vagrant up` (Virtualbox, OSX)

**Expected behavior**
I expect this to run smoothly. Everything runs when using runTests.sh.

**System (lsb_release -a or similar):**
Virtualbox, OSX
ansible-core              2.15.8
ansible-lint              6.22.2

**Additional context**
It might be that you are not using `vagrant up` anymore and that what I am doing is an outdated procedure but since I want to use this playbook, I will need to do `vagrant up` on my side. What am I doing wrong?

**Comment by konstruktoid** [comment]
Hi @jdaln, and thanks, I'm just happy someone finds the role useful :)

I'll have a look at the Vagrant file as soon as possible

**Comment by jdaln** [comment]
Thank you @konstruktoid ! It might just be that I need to switch to Molecule instead of Vagrant. I was thinking that molecule is more for roles testing, in my case, I was planning to run several ansible playbooks to see that everything works (which I did with Vagrant in the past).

**Comment by konstruktoid** [comment]
`molecule` might be a better option since it will run a compete test sequence with verification as well, but `vagrant` should work nonetheless

**Comment by konstruktoid** [comment]
Sorry for the delay @jdaln, but I believe it's fixed with https://github.com/konstruktoid/ansible-role-hardening/pull/591

**Comment by jdaln** [comment]
Thank you @konstruktoid ! New bug found but I will open a new issue. I would send a merge request but I think that it needs an informed decision.
