### ISSUE TITLE
[BUG] Invalid WEB_CMD configuration option: command is non-existent or not executable: curl in validate configuration

### ISSUE THREAD

**Issue by jdaln** [konstruktoid/ansible-role-hardening#592]
Hello!

**Describe the bug**
Running `vagrant up` results in 
```
TASK [konstruktoid.hardening : Validate configuration] *************************
fatal: [bullseye_vlan]: FAILED! => {"changed": false, "cmd": ["rkhunter", "--config-check", "--enable", "all", "--disable", "none"], "delta": "0:00:01.077572", "end": "2024-04-05 08:15:25.302208", "msg": "non-zero return code", "rc": 1, "start": "2024-04-05 08:15:24.224636", "stderr": "", "stderr_lines": [], "stdout": "Invalid WEB_CMD configuration option: command is non-existent or not executable: curl", "stdout_lines": ["Invalid WEB_CMD configuration option: command is non-existent or not executable: curl"]}

```

**To Reproduce**
Run `vagrant up` (Virtualbox, OSX)

**Expected behavior**
I expect this to run without errors.

**System (lsb_release -a or similar):**
Virtualbox, OSX
ansible-core              2.15.8
ansible-lint              6.22.2

**Additional context**
This is probably caused by https://github.com/konstruktoid/ansible-role-hardening/blob/4bae6610f263fb08135fb8af66d66dc18b18cc12/defaults/main/suid_sgid_blocklist.yml#L85 but how do you want to go about it in this Vagrant testing context?

**Comment by konstruktoid** [comment]
the Vagrant boxes were missing `curl`, and is soon fixed

**Comment by konstruktoid** [comment]
https://github.com/konstruktoid/ansible-role-hardening/pull/593

**Comment by jdaln** [comment]
Works, thank you! Found another one but I'll followup with PRs
