### ISSUE TITLE
How do you use this on an existing server?

### ISSUE THREAD

**Issue by d3netxer** [konstruktoid/ansible-role-hardening#6]
How do you use this on an existing server? Do I clone the repo and run runPlaybook.sh? Why is vagrant required?

**Comment by konstruktoid** [comment]
Hi @d3netxer, please look at https://github.com/konstruktoid/ansible-role-hardening#example-playbook and https://github.com/konstruktoid/ansible-role-hardening#testing. The short version is that if you're running locally you'll need to copy the role to your local Ansible role directory.
A playbook would look similar too
```
---
- hosts: all
  serial: 50%
    - { role: konstruktoid.hardening, sshd_admin_net: [10.0.0.0/24] }
...
```

The role is also available at https://galaxy.ansible.com/konstruktoid/hardening/.

**Comment by konstruktoid** [comment]
Oh, and Vagrant is only used for local testing using the `runPlaybook.sh` script.

**Comment by konstruktoid** [comment]
Updated https://github.com/konstruktoid/ansible-role-hardening#testing, https://github.com/konstruktoid/ansible-role-hardening/pull/8/commits/9b99b9219ccc3ee708725c9dec1e3f740592d3ba
