### ISSUE TITLE
[Feature] - allow adding group to exclude hide processes

### ISSUE THREAD

**Issue by limosek** [konstruktoid/ansible-role-hardening#62]
It would be nice to have an option to set group which has access to /proc for seeing other processes (like for zabbix agent)

More info here:
https://www.cyberciti.biz/faq/linux-hide-processes-from-other-users/

I had to manually add gid=zabbix to fstab entry. But this would probably need some variable which would be better.

**Comment by konstruktoid** [comment]
Yeah, good idea.
Will add.

**Comment by limosek** [comment]
Thank you!
