### ISSUE TITLE
[Feature] - detection of virtual host

### ISSUE THREAD

**Issue by limosek** [konstruktoid/ansible-role-hardening#63]
There is an detection of BIOS and if it is VMware, open-vm-tools are installed automatically.
For hosts virtualized by kvm, name of BIOS is SeaBIOS.
If BIOS is SeaBIOS or ansible_chassis_vendor is QEMU, open-vm-tools should be installed too.

```
    "ansible_architecture": "x86_64",
        "ansible_bios_date": "04/01/2014",
        "ansible_bios_vendor": "SeaBIOS",
        "ansible_bios_version": "rel-1.14.0-0-g155821a1990b-prebuilt.qemu.org",
        "ansible_board_asset_tag": "NA",
        "ansible_board_name": "NA",
        "ansible_board_serial": "NA",
        "ansible_board_vendor": "NA",
        "ansible_board_version": "NA",
        "ansible_chassis_asset_tag": "NA",
        "ansible_chassis_serial": "NA",
        "ansible_chassis_vendor": "QEMU",
        "ansible_chassis_version": "pc-i440fx-5.2",
```

**Comment by konstruktoid** [comment]
Haven't played around with qemu, but isn't there any qemu specific tools?

**Comment by limosek** [comment]
Sorry, you are correct. Name of package is qemu-guest-agent , which is same on debian and centos.

**Comment by konstruktoid** [comment]
Hopefully added with https://github.com/konstruktoid/ansible-role-hardening/commit/e5ff55523b0ee783073b8e11cdf10272c559a3a5
