### ISSUE TITLE
[BUG] - missing libpam-cap package to install as mandatory

### ISSUE THREAD

**Issue by limosek** [konstruktoid/ansible-role-hardening#64]
**Describe the bug**
After hardenize, pam complains about missing library:
Apr 28 17:11:19 fcpa-fc-cz saslauthd[737]: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory

Seems that pam_cap is referenced in hardening template common-auth.j2 but it is not installed as mandatory package

**Expected behavior**
add libpam-cap to required debian packages

**Comment by konstruktoid** [comment]
Added in https://github.com/konstruktoid/ansible-role-hardening/commit/6e3695ec3151605e769d314c87a4a81a20118bd3

**Comment by limosek** [comment]
Thank you!
