### ISSUE TITLE
[BUG]  [EC2] [GRUB] [UBUNTU] "The conditional check 'item.mode|int > 0400' failed".

### ISSUE THREAD

**Issue by fentonfentonfenton** [konstruktoid/ansible-role-hardening#70]
**Describe the bug**
Hi!
Hardening fails on:

```
 amazon-ebs: TASK [konstruktoid.hardening : set grub config permissions] ********************[0m
[0;32m    amazon-ebs: fatal: [default]: FAILED! => {"msg": "The conditional check 'item.mode|int > 0400' failed. The error was: template error while templating string: expected token 'end of statement block', got 'integer'. String: {% if item.mode|int > 0400 %} True {% else %} False {% endif %}\n\nThe error appears to be in '/root/.ansible/roles/konstruktoid.hardening/tasks/post.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: set grub config permissions\n  ^ here\n"}[0m
```

On a server:

```
stat -c "%a %n" /boot/grub/grub.cfg
444 /boot/grub/grub.cfg
```

```
stat -c "%a %n" /boot/grub/grubenv
644 /boot/grub/grubenv
```

```
ls /boot/grub/
default           fonts/            gfxblacklist.txt  grub.cfg          grubenv           i386-pc/          locale/           menu.lst          menu.lst~         unicode.pf2
```

**To Reproduce**
Running the playbook  `v1.3.2` on an `AWS` `ubuntu` `EC2` instance

**Expected behavior**
Ansible finds the `grub` config files and set them to `400`

**System (lsb_release -a or similar):**
```
Distributor ID: Ubuntu
Release:        20.04
Codename:       focal
```

**Additional context**

Is there anything we can do to override this in settings?

THANKS! :)

**Comment by konstruktoid** [comment]
Hi @fentonfentonfenton and thanks for reporting this.

I don't have access to a AWS instance at the moment, so I can't test and update the code on that platform.

`CIS-UBUNTU2004-1.4.3` is the tag you can exclude in the master branch, but that's not currently available in the released Galaxy version.

Will go through the role and push a new release as soon as possible.

**Comment by fentonfentonfenton** [comment]
Thanks a lot for the advice, I am currently trying to use `master` instead :) A new version of the role would be AWESOME!

**Comment by fentonfentonfenton** [comment]
Got a successful run of `master` so you can close this, it's good for us to use a v`ersion` however, for compliance reasons, so will be looking out for the next release!


cheers.

**Comment by konstruktoid** [comment]
> Got a successful run of `master` so you can close this, it's good for us to use a v`ersion` however, for compliance reasons, so will be looking out for the next release!
> 
> 
> cheers.

Great! Will fix a new release and notify you.

**Comment by konstruktoid** [comment]
Hi again @fentonfentonfenton and sorry for the delay.
https://github.com/konstruktoid/ansible-role-hardening/releases/tag/v1.4.0 has been release.
