### ISSUE TITLE
Ansible galaxy Update

### ISSUE THREAD

**Issue by cleberb** [konstruktoid/ansible-role-hardening#700]
Ansible galaxy update required:

![image](https://github.com/user-attachments/assets/25b706af-8a66-4ba9-869b-77da9a7ccd7d)

**Comment by jdaln** [comment]
@cleberb I believe that the ansible-galaxy method is deprecated, if you look at https://github.com/konstruktoid/ansible-role-hardening?tab=readme-ov-file#requirements, there is:
```
    src: https://github.com/konstruktoid/ansible-role-hardening.git
```
This is probably to transparently guarantee the provenance of the role.

**Comment by konstruktoid** [comment]
Thanks for answering @jdaln, and yes, using a GIT source is the perferred method since Ansible Galaxy has been broken in so many ways for an extended period of time.
