### ISSUE TITLE
[BUG] The remark about modprobe in README

### ISSUE THREAD

**Issue by melak** [konstruktoid/ansible-role-hardening#71]
**Describe the bug**
A section in the readme says
> Setting `block_blacklisted: true` will actually block, or disable, any `blacklisted` kernel modules. The reasoning behind this is that a blacklisted module can still be loaded manually with `modprobe module_name`. Using `install module_name /bin/true` prevents this.

It won't actually _block_ or _disable_ loading of modules. It _will_ block `modprobe`, that's true enough, but there's still `insmod`, which will not even bat an eye on modprobe's configuration. While `insmod` may get a tad bit tedious with modules that have dependencies, it's still perfectly possible to load any module with it. A casual reader, or perhaps someone less familiar with Linux, might misconstrue the statement as "module disabled for good", whereas in reality it's more like "_automatic loading of_ module" is disabled for good (even if the "automatic loading" is somewhat of the manual persuasion - I'm sure you get what I'm saying).

The only way to _really_ disable modules (that I know of, anyway) is `kernel.modules_disabled`. It however is global and irreversible (without a reboot).

An alternative method might be truly deleting the offending modules from the file system and using `dpkg --path-exclude` (`/etc/dpkg/dpkg.cfg.d/` droplets) where available - I'm assuming other package managers must have similar facilities.

**Comment by konstruktoid** [comment]
Hi @melak and thanks for reporting this.
You're correct and I'll will update the documentation.

And also thanks for reminding me about adding a `kernel.modules_disabled` variable.
