### ISSUE TITLE
Possibly incomplete compiler handling

### ISSUE THREAD

**Issue by melak** [konstruktoid/ansible-role-hardening#72]
https://github.com/konstruktoid/ansible-role-hardening/blob/1346f766664c12803c62f8f994a00648ac4bb93b/defaults/main/compilers.yml#L2

(I am not an Ansible person by any stretch of the imagination) this does not seem to account for the (not uncommon) case when one might have more than one version of a compiler (or multiple compilers) installed (even in a server context).

```
$ ls -l /usr/bin/cc /usr/bin/gcc /usr/bin/gcc-? /usr/bin/clang-?
lrwxrwxrwx 1 root root 20 Feb 24  2018 /usr/bin/cc -> /etc/alternatives/cc
lrwxrwxrwx 1 root root 23 Jan 31  2020 /usr/bin/clang-9 -> ../lib/llvm-9/bin/clang
lrwxrwxrwx 1 root root  5 May 20  2019 /usr/bin/gcc -> gcc-7
lrwxrwxrwx 1 root root 22 Dec  4  2019 /usr/bin/gcc-7 -> x86_64-linux-gnu-gcc-7
lrwxrwxrwx 1 root root 22 Mar 10  2020 /usr/bin/gcc-8 -> x86_64-linux-gnu-gcc-8
```

As far as I understand this task (or whatever it is called :) would leave `gcc-8` in this example open (granted, locked-down `as` mitigates that). However, I suppose Clang would also need to be accounted for, as it doesn't necessarily need to use GNU as, so the current state completely misses it.

You might plausibly consider including Rust and Go on this list as well, "just in case".

On platforms where supported (deb-derived), using `dpkg-statoverride` would probably be a good thing. Don't know if RPM and friends have similar facilities.

**Comment by konstruktoid** [comment]
Hi again @melak and you're correct.
The task covers the basic and most common cases from e.g. the CIS benchmarks.

Definitely room for improvement.

Will have a closer look at that task as soon as possible.

**Comment by konstruktoid** [comment]
Believe this is fixed with https://github.com/konstruktoid/ansible-role-hardening/commit/e5fe2c9f9e65c7bf8fa3849fa3202241bc5a212a
