### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by martin-carpenter** [konstruktoid/ansible-role-hardening#74]
**Describe the bug**
In Debian 11.0.0 users can no longer login to the console, switch user with su or perform elivated commands with sudo after play name: common-auth in tasks/password.yml is run. The user can sudo if named in sudoers, but not if the group is named only. Login via SSH still functions correctly.

**To Reproduce**
Run role on Debian 11.0.0 or just play name: common-auth in tasks/password.yml then attempt to perform su from any non-root user to any other user, or perform any sudo command as a user in the sudo group with %sudo in /etc/sudoers.

**Expected behavior**
Console login, su and sudo function as normal.

**Additional context**
Fresh install on bare metal. This result is guaranteed every time.

**Comment by konstruktoid** [comment]
Thanks for opening this issue @martin-carpenter and I'll have a look at it as soon as possible.

**Comment by konstruktoid** [comment]
Hi again @martin-carpenter and so sorry for the late reply.
I've updated the faillock configuration and it all seems to work now.
Please test the current master branch.

**Comment by martin-carpenter** [comment]
Hi @konstruktoid, thanks for taking a look at the issue and resolving it so quickly.

I have given it a go with my system and it works perfectly! Great stuff. :)
